### ISSUE TITLE
Add styling to "Back" and "Top" buttons on dynamic blog posts

### ISSUE THREAD

**Issue by maxwelldemaio** [maxwelldemaio/max-nextjs#1]
File: https://github.com/maxwelldemaio/max-nextjs/blob/main/pages/posts/[id].js
- [x] Add blue styling to back button (same as other pages)
- [x] Add blue styling to top button

**Comment by suraj-001** [comment]
Can i try 1,2 nd option? and i didn't understand first option can you please explain your expactations by some pic or something like that , thank you!

**Comment by maxwelldemaio** [comment]
Hey Suraj, thanks for replying! Yes just the first two tasks would be perfectly fine. I'll separate the last task into its own separate issue.

If you just add the attribute `className="underline text-blue-400 hover:text-blue-600"` to both the "Back" and "Top" anchor tags that should do the trick! This will add tailwind styling to both. An example would be the bottom of the "posts" page here: https://github.com/maxwelldemaio/max-nextjs/blob/main/pages/posts/index.js

Feel free to let me know if you have any troubles

**Comment by maxwelldemaio** [comment]
> Can i try 1,2 nd option? and i didn't understand first option can you please explain your expactations by some pic or something like that , thank you!

Hey Suraj, thanks for replying! Yes just the first two tasks would be perfectly fine. I'll separate the last task into its own separate issue.

If you just add the attribute `className="underline text-blue-400 hover:text-blue-600"` to both the "Back" and "Top" anchor tags that should do the trick! This will add tailwind styling to both. An example would be the bottom of the "posts" page here: https://github.com/maxwelldemaio/max-nextjs/blob/main/pages/posts/index.js

Feel free to let me know if you have any troubles

**Comment by suraj-001** [comment]
hey you closed the issue i am totally bigginer so trying to explore things is that issue is close now? let me know if you have any update

**Comment by maxwelldemaio** [comment]
Hey Suraj, this issue was solved with #7 

Please feel free to keep an eye out if I create any other issues!
